name: B12Clans
version: 1.0.0
main: com.br.b12clans.Main
api-version: 1.21
author: Eduardo12B
description: Sistema de clãs
website: https://github.com/TheEternalDark/B12Clan

softdepend: [PlaceholderAPI]

commands:
  clan:
    description: Comando principal do sistema de clãs
    usage: /clan <subcomando>
    permission: b12clans.use
    permission-message: §cVocê não tem permissão para usar este comando!

permissions:
  b12clans.use:
    description: Permissão básica para usar comandos de clã
    default: true
  b12clans.criar:
    description: Permissão para criar clãs
    default: true
  b12clans.admin:
    description: Permissões administrativas do plugin
    default: op
  b12clans.promover:
    description: Permissão para promover membros do clã
    default: op
  b12clans.rebaixar:
    description: Permissão para rebaixar membros do clã
    default: op
